name: mhu_flutter_camera
description: Camera specific utilities for Flutter projects
version: 1.0.0
repository: https://github.com/maprohu/mhu_flutter_camera

environment:
  sdk: ^3.0.5

#dependency_overrides:
#  mhu_dart_commons:
#    path: ../mhu_dart_commons
#  mhu_dart_proto:
#    path: ../mhu_dart_proto
#  mhu_dart_model:
#    path: ../mhu_dart_model
#  mhu_flutter_commons:
#    path: ../mhu_flutter_commons
#  mhu_dart_builder:
#    path: ../mhu_dart_builder

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.4.0
  image: ^4.0.17
  camera: ^0.10.5+2
  collection: ^1.17.1
  fast_immutable_collections: ^9.1.5
  rxdart: ^0.27.7

  mhu_dart_proto: ^1.0.2
  mhu_dart_model: ^1.0.2
  mhu_dart_commons: ^1.0.8
  mhu_flutter_commons: ^1.0.5
  protobuf: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  mhu_dart_builder: ^1.0.2
